using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;
using UnityEngine.Events;

namespace UnityRFramework.Expansion
{
    [Serializable]
    internal sealed class UIBindingDraft
    {
        public string FieldName = string.Empty;
        public bool IsArray;
        public List<string> EventMemberNames = new List<string>();
        public List<GameObject> Nodes = new List<GameObject>();
        public List<Component> Components = new List<Component>();
    }

    internal sealed class UIBindingEventDescriptor
    {
        public string MemberName;
        public Type[] ArgumentTypes;

        public string DisplayName => MemberName + "(" + string.Join(
            ", ",
            ArgumentTypes.Select(type => type.FullName)) + ")";
    }

    internal sealed class UIBindingValidationResult
    {
        public readonly List<string> Errors = new List<string>();

        public bool IsValid => Errors.Count == 0;
    }

    /// <summary>
    /// 校验显式选择的 UI 组件，并生成可重复覆盖的 partial 引用代码。
    /// </summary>
    internal static class UIBindingCodeGenerator
    {
        private const string GeneratedHeader = "// <auto-generated> UnityRFramework UI bindings. </auto-generated>";
        private const string FieldMarker = "// BindingField: ";

        private static readonly HashSet<string> Keywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
            "checked", "class", "const", "continue", "decimal", "default", "delegate", "do",
            "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed",
            "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface",
            "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator",
            "out", "override", "params", "private", "protected", "public", "readonly", "ref",
            "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong",
            "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        };

        public static UIBindingValidationResult Validate(
            MonoBehaviour target,
            IReadOnlyList<UIBindingDraft> bindings)
        {
            if (target == null)
            {
                UIBindingValidationResult nullTargetResult =
                    new UIBindingValidationResult();
                nullTargetResult.Errors.Add("请选择承载生成字段的 MonoBehaviour。\n");
                return nullTargetResult;
            }

            Type targetType = target.GetType();
            MonoScript script = MonoScript.FromMonoBehaviour(target);
            string scriptPath = script == null ? string.Empty : AssetDatabase.GetAssetPath(script);
            UIBindingValidationResult result = Validate(
                targetType,
                target.transform,
                scriptPath,
                GetOutputPath(target),
                bindings);
            if (!EditorUtility.IsPersistent(target)
                && string.IsNullOrEmpty(target.gameObject.scene.path))
            {
                result.Errors.Add("目标场景尚未保存，无法跨脚本编译自动回填。\n");
            }

            return result;
        }

        internal static UIBindingValidationResult Validate(
            Type targetType,
            Transform targetRoot,
            string scriptPath,
            string outputPath,
            IReadOnlyList<UIBindingDraft> bindings)
        {
            UIBindingValidationResult result = new UIBindingValidationResult();
            if (targetType.IsNested || targetType.IsGenericType)
            {
                result.Errors.Add("目标脚本必须是非嵌套、非泛型 MonoBehaviour。\n");
            }

            if (targetRoot == null)
            {
                result.Errors.Add("目标脚本节点已丢失。\n");
            }

            if (string.IsNullOrEmpty(scriptPath))
            {
                result.Errors.Add("无法定位目标脚本文件。\n");
            }
            else if (!SourceDeclaresPartial(scriptPath, targetType.Name))
            {
                result.Errors.Add($"目标类 {targetType.FullName} 必须声明为 partial。\n");
            }

            if (bindings == null || bindings.Count == 0)
            {
                result.Errors.Add("至少添加一个绑定字段。\n");
                return result;
            }

            HashSet<string> fieldNames = new HashSet<string>(StringComparer.Ordinal);
            HashSet<string> handlerNames = new HashSet<string>(StringComparer.Ordinal);
            HashSet<int> componentIds = new HashSet<int>();
            HashSet<string> oldGeneratedFields = ReadGeneratedFieldNames(outputPath);
            HashSet<string> oldGeneratedHandlers = ReadGeneratedHandlerNames(outputPath);

            string targetAssemblyName = GetAssemblyName(scriptPath);
            HashSet<string> targetAssemblyReferences =
                GetAssemblyReferences(targetAssemblyName);

            for (int i = 0; i < bindings.Count; i++)
            {
                UIBindingDraft binding = bindings[i];
                string label = $"第 {i + 1} 项";
                if (binding == null)
                {
                    result.Errors.Add($"{label}为空。\n");
                    continue;
                }

                if (!IsValidIdentifier(binding.FieldName))
                {
                    result.Errors.Add($"{label}字段名 '{binding.FieldName}' 不是合法的 C# 标识符。\n");
                }
                else if (!fieldNames.Add(binding.FieldName))
                {
                    result.Errors.Add($"字段名 '{binding.FieldName}' 重复。\n");
                }
                else
                {
                    FieldInfo existingField = targetType.GetField(
                        binding.FieldName,
                        BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                    if (existingField != null && !oldGeneratedFields.Contains(binding.FieldName))
                    {
                        result.Errors.Add($"字段 '{binding.FieldName}' 已在业务脚本中声明。\n");
                    }
                }

                int count = binding.Components == null ? 0 : binding.Components.Count;
                if (count == 0)
                {
                    result.Errors.Add($"{label}没有选择组件。\n");
                    continue;
                }

                if (!binding.IsArray && count != 1)
                {
                    result.Errors.Add($"普通字段 '{binding.FieldName}' 只能选择一个组件。\n");
                }

                Type componentType = null;
                for (int componentIndex = 0; componentIndex < count; componentIndex++)
                {
                    Component component = binding.Components[componentIndex];
                    if (component == null)
                    {
                        result.Errors.Add($"字段 '{binding.FieldName}' 存在丢失引用。\n");
                        continue;
                    }

                    if (component.transform != targetRoot
                        && !component.transform.IsChildOf(targetRoot))
                    {
                        result.Errors.Add($"组件 '{component.name}' 不在目标脚本节点或其子节点中。\n");
                    }

                    if (!componentIds.Add(component.GetInstanceID()))
                    {
                        result.Errors.Add($"组件 '{GetTransformPath(targetRoot, component.transform)}' 被重复绑定。\n");
                    }

                    if (componentType == null)
                    {
                        componentType = component.GetType();
                    }
                    else if (component.GetType() != componentType)
                    {
                        result.Errors.Add($"数组字段 '{binding.FieldName}' 中的组件类型不一致。\n");
                    }
                }

                ValidateEvent(
                    binding,
                    componentType,
                    targetType,
                    oldGeneratedHandlers,
                    handlerNames,
                    result);

                ValidateAssemblyReference(
                    binding,
                    componentType,
                    targetAssemblyName,
                    targetAssemblyReferences,
                    result);
            }

            return result;
        }

        public static string Generate(
            MonoBehaviour target,
            IReadOnlyList<UIBindingDraft> bindings)
        {
            UIBindingValidationResult validation = Validate(target, bindings);
            if (!validation.IsValid)
            {
                throw new InvalidOperationException(string.Join(string.Empty, validation.Errors));
            }

            return Generate(target.GetType(), bindings);
        }

        internal static string Generate(
            Type targetType,
            IReadOnlyList<UIBindingDraft> bindings)
        {
            StringBuilder builder = new StringBuilder(2048);
            builder.AppendLine(GeneratedHeader);
            builder.AppendLine();
            if (!string.IsNullOrEmpty(targetType.Namespace))
            {
                builder.Append("namespace ").Append(targetType.Namespace).AppendLine();
                builder.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(targetType.Namespace) ? string.Empty : "    ";
            builder.Append(indent)
                .Append(targetType.IsPublic ? "public" : "internal")
                .Append(" partial class ")
                .Append(targetType.Name)
                .AppendLine();
            builder.Append(indent).AppendLine("{");

            for (int i = 0; i < bindings.Count; i++)
            {
                UIBindingDraft binding = bindings[i];
                Type componentType = binding.Components[0].GetType();
                string typeName = GetCSharpTypeName(componentType) + (binding.IsArray ? "[]" : string.Empty);
                builder.Append(indent).Append("    ").Append(FieldMarker).AppendLine(binding.FieldName);
                builder.Append(indent).AppendLine("    [global::UnityEngine.SerializeField]");
                builder.Append(indent).Append("    private ").Append(typeName).Append(' ')
                    .Append(binding.FieldName).AppendLine(";");

                List<UIBindingEventDescriptor> events = GetSelectedEvents(binding);
                for (int eventIndex = 0; eventIndex < events.Count; eventIndex++)
                {
                    AppendEventMethods(
                        builder,
                        indent + "    ",
                        binding,
                        events[eventIndex]);
                }

                if (i < bindings.Count - 1)
                {
                    builder.AppendLine();
                }
            }

            builder.Append(indent).AppendLine("}");
            if (!string.IsNullOrEmpty(targetType.Namespace))
            {
                builder.AppendLine("}");
            }

            return builder.ToString().Replace("\r\n", "\n");
        }

        public static string GetOutputPath(MonoBehaviour target)
        {
            if (target == null)
            {
                return string.Empty;
            }

            MonoScript script = MonoScript.FromMonoBehaviour(target);
            string scriptPath = script == null ? string.Empty : AssetDatabase.GetAssetPath(script);
            if (string.IsNullOrEmpty(scriptPath))
            {
                return string.Empty;
            }

            string directory = Path.GetDirectoryName(scriptPath)?.Replace('\\', '/');
            return string.IsNullOrEmpty(directory)
                ? target.GetType().Name + ".Bindings.g.cs"
                : directory + "/" + target.GetType().Name + ".Bindings.g.cs";
        }

        public static string GetTransformPath(Transform root, Transform target)
        {
            if (root == target)
            {
                return root.name;
            }

            List<string> names = new List<string>();
            Transform current = target;
            while (current != null && current != root)
            {
                names.Add(current.name);
                current = current.parent;
            }

            if (current != root)
            {
                return target == null ? "<Missing>" : target.name;
            }

            names.Add(root.name);
            names.Reverse();
            return string.Join("/", names);
        }

        public static List<UIBindingEventDescriptor> GetSupportedEvents(
            Type componentType)
        {
            List<UIBindingEventDescriptor> result =
                new List<UIBindingEventDescriptor>();
            if (componentType == null)
            {
                return result;
            }

            Dictionary<string, UIBindingEventDescriptor> events =
                new Dictionary<string, UIBindingEventDescriptor>(StringComparer.Ordinal);
            PropertyInfo[] properties = componentType.GetProperties(
                BindingFlags.Instance | BindingFlags.Public);
            for (int i = 0; i < properties.Length; i++)
            {
                PropertyInfo property = properties[i];
                if (property.GetIndexParameters().Length == 0
                    && property.GetGetMethod() != null)
                {
                    AddEventDescriptor(events, property.Name, property.PropertyType);
                }
            }

            FieldInfo[] fields = componentType.GetFields(
                BindingFlags.Instance | BindingFlags.Public);
            for (int i = 0; i < fields.Length; i++)
            {
                AddEventDescriptor(events, fields[i].Name, fields[i].FieldType);
            }

            result.AddRange(events.Values.OrderBy(item => item.MemberName));
            return result;
        }

        public static string GetHandlerMethodName(
            UIBindingDraft binding,
            string eventMemberName)
        {
            string stem = ToPascalCase(binding.FieldName);
            string eventStem = eventMemberName;
            if (eventStem.Length > 2
                && eventStem.StartsWith("on", StringComparison.OrdinalIgnoreCase)
                && char.IsUpper(eventStem[2]))
            {
                eventStem = eventStem.Substring(2);
            }

            return "Handle" + stem + ToPascalCase(eventStem);
        }

        private static void ValidateEvent(
            UIBindingDraft binding,
            Type componentType,
            Type targetType,
            HashSet<string> oldGeneratedHandlers,
            HashSet<string> handlerNames,
            UIBindingValidationResult result)
        {
            if (binding.EventMemberNames == null
                || binding.EventMemberNames.Count == 0)
            {
                return;
            }

            if (binding.IsArray)
            {
                result.Errors.Add($"数组字段 '{binding.FieldName}' 不支持自动事件入口。\n");
                return;
            }

            Dictionary<string, UIBindingEventDescriptor> supported =
                GetSupportedEvents(componentType).ToDictionary(
                    item => item.MemberName,
                    StringComparer.Ordinal);
            HashSet<string> selectedEvents = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < binding.EventMemberNames.Count; i++)
            {
                string eventName = binding.EventMemberNames[i];
                if (!selectedEvents.Add(eventName))
                {
                    result.Errors.Add($"字段 '{binding.FieldName}' 的事件 '{eventName}' 重复。\n");
                    continue;
                }

                if (!supported.TryGetValue(eventName, out UIBindingEventDescriptor descriptor))
                {
                    result.Errors.Add(
                        $"字段 '{binding.FieldName}' 的组件类型不支持事件 '{eventName}'。\n");
                    continue;
                }

                string handlerName = GetHandlerMethodName(binding, eventName);
                if (!handlerNames.Add(handlerName))
                {
                    result.Errors.Add($"事件方法 '{handlerName}' 重复。\n");
                }

                MethodInfo existingMethod = targetType.GetMethod(
                    handlerName,
                    BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
                    null,
                    descriptor.ArgumentTypes,
                    null);
                if (existingMethod != null
                    && !oldGeneratedHandlers.Contains(handlerName))
                {
                    result.Errors.Add($"事件方法 '{handlerName}' 已在业务脚本中声明。\n");
                }
            }
        }

        private static void AppendEventMethods(
            StringBuilder builder,
            string indent,
            UIBindingDraft binding,
            UIBindingEventDescriptor descriptor)
        {
            string handlerName = GetHandlerMethodName(binding, descriptor.MemberName);
            string callbackName = "On" + handlerName.Substring("Handle".Length);
            List<string> parameters = new List<string>();
            List<string> arguments = new List<string>();
            for (int i = 0; i < descriptor.ArgumentTypes.Length; i++)
            {
                string name = descriptor.ArgumentTypes.Length == 1 ? "value" : "arg" + i;
                parameters.Add(GetCSharpTypeName(descriptor.ArgumentTypes[i]) + " " + name);
                arguments.Add(name);
            }

            builder.AppendLine();
            builder.Append(indent).Append("public void ").Append(handlerName).Append('(')
                .Append(string.Join(", ", parameters)).AppendLine(")");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    ").Append(callbackName).Append('(')
                .Append(string.Join(", ", arguments)).AppendLine(");");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).Append("partial void ").Append(callbackName).Append('(')
                .Append(string.Join(", ", parameters)).AppendLine(");");
        }

        private static string GetCSharpTypeName(Type type)
        {
            if (type.IsArray)
            {
                return GetCSharpTypeName(type.GetElementType()) + "[]";
            }

            if (!type.IsGenericType)
            {
                return "global::" + type.FullName.Replace('+', '.');
            }

            string name = type.GetGenericTypeDefinition().FullName;
            name = name.Substring(0, name.IndexOf('`')).Replace('+', '.');
            return "global::" + name + "<" + string.Join(
                ", ",
                type.GetGenericArguments().Select(GetCSharpTypeName)) + ">";
        }

        private static void AddEventDescriptor(
            IDictionary<string, UIBindingEventDescriptor> events,
            string memberName,
            Type eventType)
        {
            if (!TryGetUnityEventArguments(eventType, out Type[] argumentTypes)
                || argumentTypes.Length > 4)
            {
                return;
            }

            events[memberName] = new UIBindingEventDescriptor
            {
                MemberName = memberName,
                ArgumentTypes = argumentTypes
            };
        }

        private static bool TryGetUnityEventArguments(
            Type eventType,
            out Type[] argumentTypes)
        {
            Type current = eventType;
            while (current != null && current != typeof(object))
            {
                if (current == typeof(UnityEvent))
                {
                    argumentTypes = Type.EmptyTypes;
                    return true;
                }

                if (current.IsGenericType)
                {
                    Type definition = current.GetGenericTypeDefinition();
                    if (definition == typeof(UnityEvent<>)
                        || definition == typeof(UnityEvent<,>)
                        || definition == typeof(UnityEvent<,,>)
                        || definition == typeof(UnityEvent<,,,>))
                    {
                        argumentTypes = current.GetGenericArguments();
                        return true;
                    }
                }

                current = current.BaseType;
            }

            argumentTypes = null;
            return false;
        }

        internal static List<UIBindingEventDescriptor> GetSelectedEvents(
            UIBindingDraft binding)
        {
            if (binding.EventMemberNames == null
                || binding.EventMemberNames.Count == 0
                || binding.Components.Count == 0
                || binding.Components[0] == null)
            {
                return new List<UIBindingEventDescriptor>();
            }

            HashSet<string> selected = new HashSet<string>(
                binding.EventMemberNames,
                StringComparer.Ordinal);
            return GetSupportedEvents(binding.Components[0].GetType())
                .Where(item => selected.Contains(item.MemberName))
                .ToList();
        }

        private static void ValidateAssemblyReference(
            UIBindingDraft binding,
            Type componentType,
            string targetAssemblyName,
            HashSet<string> references,
            UIBindingValidationResult result)
        {
            if (componentType == null
                || string.IsNullOrEmpty(targetAssemblyName)
                || targetAssemblyName.StartsWith("Assembly-CSharp", StringComparison.Ordinal))
            {
                return;
            }

            HashSet<Type> requiredTypes = new HashSet<Type> { componentType };
            List<UIBindingEventDescriptor> events = GetSelectedEvents(binding);
            for (int i = 0; i < events.Count; i++)
            {
                for (int argumentIndex = 0;
                     argumentIndex < events[i].ArgumentTypes.Length;
                     argumentIndex++)
                {
                    requiredTypes.Add(events[i].ArgumentTypes[argumentIndex]);
                }
            }

            foreach (Type requiredType in requiredTypes)
            {
                string requiredAssembly = requiredType.Assembly.GetName().Name;
                if (requiredAssembly == targetAssemblyName
                    || references.Contains(requiredAssembly))
                {
                    continue;
                }

                result.Errors.Add(
                    $"目标程序集 '{targetAssemblyName}' 未引用组件或事件所需程序集 "
                    + $"'{requiredAssembly}'。请在对应 asmdef 的 Assembly Definition "
                    + "References 中添加该引用。\n");
            }
        }

        private static string GetAssemblyName(string scriptPath)
        {
            if (string.IsNullOrEmpty(scriptPath))
            {
                return string.Empty;
            }

            string name = CompilationPipeline.GetAssemblyNameFromScriptPath(scriptPath);
            return string.IsNullOrEmpty(name)
                ? string.Empty
                : Path.GetFileNameWithoutExtension(name);
        }

        private static HashSet<string> GetAssemblyReferences(string assemblyName)
        {
            HashSet<string> result = new HashSet<string>(StringComparer.Ordinal);
            if (string.IsNullOrEmpty(assemblyName))
            {
                return result;
            }

            UnityEditor.Compilation.Assembly assembly = CompilationPipeline
                .GetAssemblies()
                .FirstOrDefault(item => item.name == assemblyName);
            if (assembly == null)
            {
                return result;
            }

            result.Add(assemblyName);
            AddAssemblyReferences(result, assembly.allReferences);
            AddAssemblyReferences(result, assembly.compiledAssemblyReferences);
            return result;
        }

        private static void AddAssemblyReferences(
            ISet<string> result,
            IEnumerable<string> references)
        {
            foreach (string reference in references)
            {
                result.Add(Path.GetFileNameWithoutExtension(reference));
            }
        }

        private static bool SourceDeclaresPartial(string scriptPath, string className)
        {
            string absolutePath = Path.GetFullPath(scriptPath);
            if (!File.Exists(absolutePath))
            {
                return false;
            }

            string source = File.ReadAllText(absolutePath);
            return Regex.IsMatch(
                source,
                @"\bpartial\s+class\s+" + Regex.Escape(className) + @"\b",
                RegexOptions.CultureInvariant);
        }

        private static bool IsValidIdentifier(string value)
        {
            return !string.IsNullOrWhiteSpace(value)
                && !Keywords.Contains(value)
                && Regex.IsMatch(value, @"^[A-Za-z_][A-Za-z0-9_]*$");
        }

        private static HashSet<string> ReadGeneratedFieldNames(string path)
        {
            HashSet<string> names = new HashSet<string>(StringComparer.Ordinal);
            if (string.IsNullOrEmpty(path) || !File.Exists(Path.GetFullPath(path)))
            {
                return names;
            }

            string[] lines = File.ReadAllLines(Path.GetFullPath(path));
            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i].Trim();
                if (line.StartsWith(FieldMarker, StringComparison.Ordinal))
                {
                    names.Add(line.Substring(FieldMarker.Length).Trim());
                }
            }

            return names;
        }

        private static HashSet<string> ReadGeneratedHandlerNames(string path)
        {
            HashSet<string> names = new HashSet<string>(StringComparer.Ordinal);
            if (string.IsNullOrEmpty(path) || !File.Exists(Path.GetFullPath(path)))
            {
                return names;
            }

            string source = File.ReadAllText(Path.GetFullPath(path));
            MatchCollection matches = Regex.Matches(
                source,
                @"\bpublic\s+void\s+(Handle[A-Za-z0-9_]+)\s*\(",
                RegexOptions.CultureInvariant);
            for (int i = 0; i < matches.Count; i++)
            {
                names.Add(matches[i].Groups[1].Value);
            }

            return names;
        }

        private static string ToPascalCase(string value)
        {
            string trimmed = value.TrimStart('_');
            if (trimmed.Length == 0)
            {
                return "Binding";
            }

            string[] parts = trimmed.Split(
                new[] { '_' },
                StringSplitOptions.RemoveEmptyEntries);
            StringBuilder builder = new StringBuilder(trimmed.Length);
            for (int i = 0; i < parts.Length; i++)
            {
                builder.Append(char.ToUpperInvariant(parts[i][0]));
                builder.Append(parts[i].Substring(1));
            }

            return builder.Length == 0 ? "Binding" : builder.ToString();
        }
    }
}
