// <auto-generated> UnityRFramework UI bindings. </auto-generated>

namespace UnityRFramework.Sample.UI
{
    public partial class UIBindTest
    {
        // BindingField: input
        [global::UnityEngine.SerializeField]
        private global::UnityEngine.UI.InputField input;

        public void HandleInputEndEdit(global::System.String value)
        {
            OnInputEndEdit(value);
        }

        partial void OnInputEndEdit(global::System.String value);

        // BindingField: input_tmp
        [global::UnityEngine.SerializeField]
        private global::TMPro.TMP_InputField input_tmp;

        public void HandleInputTmpSubmit(global::System.String value)
        {
            OnInputTmpSubmit(value);
        }

        partial void OnInputTmpSubmit(global::System.String value);

        // BindingField: btn
        [global::UnityEngine.SerializeField]
        private global::UnityEngine.UI.Button btn;

        public void HandleBtnClick()
        {
            OnBtnClick();
        }

        partial void OnBtnClick();

        // BindingField: text
        [global::UnityEngine.SerializeField]
        private global::UnityEngine.UI.Text text;

        // BindingField: icon
        [global::UnityEngine.SerializeField]
        private global::UnityEngine.UI.Image[] icon;
    }
}
